export const busTimeline = [
	{
		id: "1",
		koridor: "1",
		tujuan: "Blok M",
		eta: "Tiba Sekarang",
		tibaPukul: "07:20",
		jarak: "0,0 km",
		crowdedness: "Penuh",
		firstHalteDeparture: "07:25", // Waktu berangkat dari halte pertama
	},
	{
		id: "2",
		koridor: "1",
		tujuan: "Blok M",
		eta: "2",
		tibaPukul: "07:22",
		jarak: "1,2 km",
		crowdedness: "Kosong",
		firstHalteDeparture: "07:27",
	},
	{
		id: "3",
		koridor: "1",
		tujuan: "Blok M",
		eta: "17",
		tibaPukul: "07:37",
		jarak: "4,5 km",
		crowdedness: "Sedang",
		firstHalteDeparture: "07:42",
	},
	{
		id: "4",
		koridor: "1",
		tujuan: "Blok M",
		eta: "22",
		tibaPukul: "07:42",
		jarak: "6,8 km",
		crowdedness: "Kosong",
		firstHalteDeparture: "07:47",
	},
];
